Add icrc1 deploy token doc
dfinity/portal pull request #1008
Opened 2023-01-25 15:02 UTC by leokazz

2023-01-27 11:04 UTC, sesi200 requested changes

2023-01-27 17:59 UTC, leokazz reviewed
Updated sidebar

2023-01-30 10:44 UTC, sesi200 commented on docs/developer-docs/integrations/icrc-1/deploy-new-token.md
> +2.  Ensure you use a recent version of `dfx`. If you don’t have `dfx` installed, follow instructions on the [Installing the SDK](../../build/install-upgrade-remove.md) section to install it.
```suggestion
2.  Ensure you use a recent version of `dfx`. If you don’t have `dfx` installed, follow instructions on the [Installing the SDK](../../build/install-upgrade-remove.mdx) section to install it.
```

2023-01-30 10:44 UTC, sesi200 approved these changes

2023-01-30 10:45 UTC, merged