add caniplay to showcase
dfinity/portal pull request #1619
Opened 2023-06-23 18:59 UTC by s1dc0des

Thank you for your contribution to the IC Developer Portal.
Before submitting your Pull Request, please make sure that:

- [ ] You have updated the [`.github/CODEOWNERS`](https://github.com/dfinity/portal/blob/master/.github/CODEOWNERS) file according to your changes.
- [ ] You have registered new documents to [`/sidebars.js`](https://github.com/dfinity/portal/blob/master/sidebars.js) if any.

2023-06-29 07:13 UTC, domwoe approved these changes

2023-06-29 08:50 UTC, sesi200 requested changes
The logo doesn't work. Usually reuploading helps.

The GH link somehow redirects back to github.com

2023-06-30 14:19 UTC, sesi200 reviewed
Still doesn't work...
<img width="1368" alt="image" src="https://github.com/dfinity/portal/assets/14757975/038bcf0b-12bb-4547-ab0b-95359bf0e8a8">

2023-06-30 14:57 UTC, s1dc0des commented
made changes. should i resolve conflicts ?

2023-07-04 09:41 UTC, sesi200 approved these changes

2023-07-04 09:43 UTC, merged