Update local-development.md
dfinity/portal pull request #1784
Opened 2023-08-11 15:02 UTC by letmejustputthishere

Thank you for your contribution to the IC Developer Portal.
Before submitting your Pull Request, please make sure that:

- [ ] You have updated the [`.github/CODEOWNERS`](https://github.com/dfinity/portal/blob/master/.github/CODEOWNERS) file according to your changes.
- [ ] You have registered new documents to [`/sidebars.js`](https://github.com/dfinity/portal/blob/master/sidebars.js) if any.

2023-08-11 15:05 UTC, jessiemongeon1 approved these changes

2023-08-11 15:05 UTC, jessiemongeon1 commented on docs/developer-docs/integrations/bitcoin/local-development.md
> +    If you're running the Rust example, use
```suggestion
    If you're running the Rust example, use the command:
```

2023-08-11 15:05 UTC, jessiemongeon1 commented on docs/developer-docs/integrations/bitcoin/local-development.md
> +    If you're running Motoko, use
```suggestion

    If you're running the Motoko example, use the command:
```

2023-08-11 20:57 UTC, ielashi requested changes
We don't need separate commands for the different languages. We just need to fix the Motoko examples's dfx.json. I'll take care of it.

2023-08-14 07:36 UTC, letmejustputthishere commented
> We don't need separate commands for the different languages. We just need to fix the Motoko examples's dfx.json. I'll take care of it.

@ielashi the initialisation arguments are still different for the two examples so i don't think there's anything you can do about that in `dfx.json`?

motoko expects [upper case variants](https://github.com/dfinity/examples/blob/d54cd27712450e77e4a398e35f0f0118eee8a47e/motoko/basic_bitcoin/src/basic_bitcoin/basic_bitcoin.did#L9) and rust expects [lower case variants](https://github.com/dfinity/examples/blob/d54cd27712450e77e4a398e35f0f0118eee8a47e/rust/basic_bitcoin/src/basic_bitcoin/basic_bitcoin.did#L9) for the init args.

so imo we still need to merge this PR

2023-08-14 07:59 UTC, ielashi commented
> > We don't need separate commands for the different languages. We just need to fix the Motoko examples's dfx.json. I'll take care of it.
> 
> @ielashi the initialisation arguments are still different for the two examples so i don't think there's anything you can do about that in `dfx.json`?
> 
> motoko expects [upper case variants](https://github.com/dfinity/examples/blob/d54cd27712450e77e4a398e35f0f0118eee8a47e/motoko/basic_bitcoin/src/basic_bitcoin/basic_bitcoin.did#L9) and rust expects [lower case variants](https://github.com/dfinity/examples/blob/d54cd27712450e77e4a398e35f0f0118eee8a47e/rust/basic_bitcoin/src/basic_bitcoin/basic_bitcoin.did#L9) for the init args.
> 
> so imo we still need to merge this PR

Both examples should use lower-case invariants, as that what is specified in the interface specification of the Bitcoin API. I addressed this, along with updating dfx.json here: https://github.com/dfinity/examples/pull/606, so we don't the change in this PR.

2023-08-14 11:02 UTC, closed without merging