feat - tbfz game <3
dfinity/portal pull request #1822
Opened 2023-08-21 19:56 UTC by franRappazzini

Thank you for your contribution to the IC Developer Portal.
Before submitting your Pull Request, please make sure that:

- [ ] You have updated the [`.github/CODEOWNERS`](https://github.com/dfinity/portal/blob/master/.github/CODEOWNERS) file according to your changes.
- [ ] You have registered new documents to [`/sidebars.js`](https://github.com/dfinity/portal/blob/master/sidebars.js) if any.

2023-08-21 19:57 UTC, sa-github-api commented
Dear @franRappazzini,

In order to potentially merge your code in this open-source repository and therefore proceed with your contribution, we need to have your approval on DFINITY's [CLA](https://github.com/dfinity/cla/blob/main/CLA.md).

If you decide to agree with it, please visit this [issue](https://github.com/dfinity/cla/issues/340) and read the instructions there. Once you have signed it, re-trigger the workflow on this PR to see if your code can be merged.

— The DFINITY Foundation

2023-08-21 20:12 UTC, jessiemongeon1 commented
Hi @franRappazzini , please resolve the conflicts within the `showcase.json` file. Thanks!

2023-08-21 23:55 UTC, franRappazzini commented
Sorry, I had not seen. That's it! Thank you!

2023-08-22 07:39 UTC, letmejustputthishere requested changes

2023-08-22 07:39 UTC, letmejustputthishere commented on showcase.json
> +    "tags": ["Games", "Metaverse", "NFT", "Bitcoin", "Wallet"],
can you please remove the Bitcoin and Wallet tags or explain why they are relevant?

2023-08-23 00:23 UTC, franRappazzini commented
@letmejustputthishere ready! thank you!

2023-10-28 07:27 UTC, jennifertrin approved these changes

2023-10-28 07:28 UTC, jennifertrin requested changes
Hello @franRappazzini, apologies, can you please follow the CLA steps above?

2024-01-23 01:19 UTC, jennifertrin approved these changes

2024-02-06 00:39 UTC, jennifertrin commented
@franRappazzini Stoll advised that you will open a PR. Please open a new PR at your earliest convenience.

2024-02-06 00:39 UTC, closed without merging