Add Ethereum canister to the showcase
dfinity/portal pull request #1825
Opened 2023-08-22 14:39 UTC by zvolin

Hi, as requested in the final demo checklist, I'm submitting the ethereum canister to the showcase.json. As it's yet a poc that has no real users, no logo etc I left a few fields empty

Thank you for your contribution to the IC Developer Portal.
Before submitting your Pull Request, please make sure that:

- [ ] You have updated the [`.github/CODEOWNERS`](https://github.com/dfinity/portal/blob/master/.github/CODEOWNERS) file according to your changes.
- [ ] You have registered new documents to [`/sidebars.js`](https://github.com/dfinity/portal/blob/master/sidebars.js) if any.

2023-08-22 14:45 UTC, zvolin commented
> Once you have signed it, re-trigger the workflow on this PR to see if your code can be merged.

it seems I cannot retrigger

2023-08-23 12:58 UTC, letmejustputthishere commented on showcase.json
> +    "description": "The Ethereum canister offers a secure and trustless way to access Ethereum blockchain data within the ICP ecosystem. Behind the scenes, it leverages the helios light Ethereum clie
can you fix `clien`

2023-08-23 13:59 UTC, zvolin commented on showcase.json
> +    "description": "The Ethereum canister offers a secure and trustless way to access Ethereum blockchain data within the ICP ecosystem. Behind the scenes, it leverages the helios light Ethereum clie
done

2023-08-23 14:49 UTC, letmejustputthishere requested changes

2023-08-23 14:49 UTC, letmejustputthishere commented on showcase.json
> +      "Ethereum", "Tools / Infrastructure",
pls remove the  trailing comma

2023-08-24 08:37 UTC, zvolin commented on showcase.json
> +      "Ethereum", "Tools / Infrastructure",
done

2023-08-24 09:15 UTC, letmejustputthishere approved these changes

2023-08-24 09:15 UTC, merged