Update custom-domain.md
dfinity/portal pull request #1863
Opened 2023-08-31 08:08 UTC by 3erikpotter

Add further context for AWS:Route53 TXT. 

Thank you for your contribution to the IC Developer Portal.
Before submitting your Pull Request, please make sure that:

- [ ] You have updated the [`.github/CODEOWNERS`](https://github.com/dfinity/portal/blob/master/.github/CODEOWNERS) file according to your changes.
- [ ] You have registered new documents to [`/sidebars.js`](https://github.com/dfinity/portal/blob/master/sidebars.js) if any.

2023-08-31 08:11 UTC, sa-github-api commented
Dear @3erikpotter,

In order to potentially merge your code in this open-source repository and therefore proceed with your contribution, we need to have your approval on DFINITY's [CLA](https://github.com/dfinity/cla/blob/main/CLA.md).

If you decide to agree with it, please visit this [issue](https://github.com/dfinity/cla/issues/347) and read the instructions there. Once you have signed it, re-trigger the workflow on this PR to see if your code can be merged.

— The DFINITY Foundation

2023-08-31 21:06 UTC, jessiemongeon1 requested changes

2023-08-31 21:06 UTC, jessiemongeon1 commented on docs/developer-docs/production/custom-domain/custom-domain.md
> +For APEX, the name has to be empty, with the value containing the key-value pair: "_canister-id:CANISTER_ID"
```suggestion
For APEX, the name has to be empty, with the value containing the key-value pair: "_canister-id:CANISTER_ID".
```

2023-08-31 21:06 UTC, jessiemongeon1 commented on docs/developer-docs/production/custom-domain/custom-domain.md
> +For non-apex (e.g. www), the name should be the standard “_canister-id.www” and value "CANISTER_ID"
```suggestion
For non-apex (e.g. www), the name should be the standard “_canister-id.www” and value "CANISTER_ID".
```

2023-09-12 16:06 UTC, jessiemongeon1 approved these changes

2023-09-12 16:06 UTC, merged