Add dFlow project to showcase
dfinity/portal pull request #2007
Opened 2023-10-16 19:11 UTC by CallForSanity

Thank you for your contribution to the IC Developer Portal.
Before submitting your Pull Request, please make sure that:

- [ ] You have updated the [`.github/CODEOWNERS`](https://github.com/dfinity/portal/blob/master/.github/CODEOWNERS) file according to your changes.
- [ ] You have registered new documents to [`/sidebars.js`](https://github.com/dfinity/portal/blob/master/sidebars.js) if any.

2023-10-16 19:13 UTC, sa-github-api commented
Dear @CallForSanity,

In order to potentially merge your code in this open-source repository and therefore proceed with your contribution, we need to have your approval on DFINITY's [CLA](https://github.com/dfinity/cla/blob/main/CLA.md).

If you decide to agree with it, please visit this [issue](https://github.com/dfinity/cla/issues/377) and read the instructions there. Once you have signed it, re-trigger the workflow on this PR to see if your code can be merged.

— The DFINITY Foundation

2023-10-17 20:25 UTC, jennifertrin requested changes

2023-10-17 20:25 UTC, jennifertrin commented on showcase.json
> +    "BPMN",
Can you please remove the BPMN tag? We only offer the project tags listed on the IC Ecosystem page here: https://internetcomputer.org/ecosystem

2023-10-18 06:06 UTC, jennifertrin approved these changes

2023-10-18 06:06 UTC, jennifertrin commented on showcase.json
> +    "BPMN",
Thank you for the update!

2023-10-18 06:06 UTC, merged