Added BTC Flower to Showcase.
dfinity/portal pull request #2035
Opened 2023-10-22 20:19 UTC by evanmcfarland

Thank you for your contribution to the IC Developer Portal.
Before submitting your Pull Request, please make sure that:

- [ ] You have updated the [`.github/CODEOWNERS`](https://github.com/dfinity/portal/blob/master/.github/CODEOWNERS) file according to your changes.
- [ ] You have registered new documents to [`/sidebars.js`](https://github.com/dfinity/portal/blob/master/sidebars.js) if any.

2023-10-22 20:21 UTC, sa-github-api commented
Dear @evanmcfarland,

In order to potentially merge your code in this open-source repository and therefore proceed with your contribution, we need to have your approval on DFINITY's [CLA](https://github.com/dfinity/cla/blob/main/CLA.md).

If you decide to agree with it, please visit this [issue](https://github.com/dfinity/cla/issues/383) and read the instructions there. Once you have signed it, re-trigger the workflow on this PR to see if your code can be merged.

— The DFINITY Foundation

2023-10-23 13:23 UTC, letmejustputthishere commented
hey, this PR only contains two images. ideally you follow the steps outlined here, the tooling should help you create an entry for the showcase.
https://github.com/dfinity/portal#showcase-submission-guidelines

2023-10-25 23:54 UTC, jennifertrin requested changes

2023-10-25 23:54 UTC, jennifertrin commented on showcase.json
> +    "video": "",
Can you please remove the video key if you do not have a video link?

2023-10-25 23:54 UTC, jennifertrin commented on showcase.json
> +    "stats": "",
Can you please remove the stats key if you do not have any stats?

2023-10-25 23:54 UTC, jennifertrin commented on showcase.json
> +    "twitter": "https://twitter.com/btcflower",
Can you please remove the comma at the end of the Twitter key value? (It expects another key value if you have a comma at the end)

2023-10-28 07:32 UTC, jennifertrin requested changes

2023-10-28 07:32 UTC, jennifertrin commented on showcase.json
> +    "logo": "/img/showcase/fpdao_logo.webp",
Hello @evanmcfarland, I believe that you uploaded PNGs. Can you please update it with the correct file type?

2023-10-28 07:32 UTC, jennifertrin commented on showcase.json
> +    "screenshots": [
Can you please update with the correct file type?

2023-10-30 15:36 UTC, jennifertrin approved these changes

2023-10-30 16:11 UTC, merged