Update showcase.json
dfinity/portal pull request #2315
Opened 2024-01-02 17:44 UTC by scott4044

Thank you for your contribution to the IC Developer Portal.
Before submitting your Pull Request, please make sure that:

- [ ] You have updated the [`.github/CODEOWNERS`](https://github.com/dfinity/portal/blob/master/.github/CODEOWNERS) file according to your changes.
- [ ] You have registered new documents to [`/sidebars.js`](https://github.com/dfinity/portal/blob/master/sidebars.js) if any.

2024-01-02 17:56 UTC, jennifertrin requested changes

2024-01-02 17:56 UTC, jennifertrin commented on showcase.json
> +  "logo": "/img/showcase/bitbasel-art-marketplace_logo.webp",
Can you please include the logo in the correct path in the PR?

2024-01-02 17:56 UTC, jennifertrin commented on showcase.json
> +  "screenshots": [
Can you please include the screenshot in the correct path in the PR?

2024-01-14 22:49 UTC, jennifertrin commented
@scott4044 Can you please review the comments and resolve them above?

2024-01-16 17:51 UTC, scott4044 commented
@jennifertrin I believe i resolved everything!

2024-01-16 18:16 UTC, jennifertrin approved these changes

2024-01-16 18:16 UTC, merged