Update showcase.json
dfinity/portal pull request #2335
Opened 2024-01-09 16:46 UTC by jdchibuk

re: "user controlled mind and body canister”

Thank you for your contribution to the IC Developer Portal.
Before submitting your Pull Request, please make sure that:

- [ ] You have updated the [`.github/CODEOWNERS`](https://github.com/dfinity/portal/blob/master/.github/CODEOWNERS) file according to your changes.
- [ ] You have registered new documents to [`/sidebars.js`](https://github.com/dfinity/portal/blob/master/sidebars.js) if any.

2024-01-09 16:48 UTC, sa-github-api commented
Dear @jdchibuk,

In order to potentially merge your code in this open-source repository and therefore proceed with your contribution, we need to have your approval on DFINITY's [CLA](https://github.com/dfinity/cla/blob/main/CLA.md).

If you decide to agree with it, please visit this [issue](https://github.com/dfinity/cla/issues/424) and read the instructions there. Once you have signed it, re-trigger the workflow on this PR to see if your code can be merged.

— The DFINITY Foundation

2024-01-11 17:10 UTC, jennifertrin requested changes
Can you please also review the CLA steps?

2024-01-11 17:10 UTC, jennifertrin commented on showcase.json
> +  "name": "user controlled mind and body canister”,
Can you please add an `id` key-value pair?

2024-01-11 17:10 UTC, jennifertrin commented on showcase.json
> +  "stats": "100% on IC mainnet”,
Can you please remove this as a stat? We normally suggest a stat to list the number of users, etc.

2024-01-11 17:10 UTC, jennifertrin commented on showcase.json
> +  "submittableId": "44190088"
Can you please include a logo as well? Please see logo key-value pair in other projects as an example and upload a logo to the correct file path.

2024-01-11 17:23 UTC, jdchibuk commented
should be updated for format now

here is CLA confirmation: https://github.com/dfinity/cla/issues/424#issuecomment-1883433708

2024-01-12 04:35 UTC, jennifertrin commented
> should be updated for format now
> 
> here is CLA confirmation: [dfinity/cla#424 (comment)](https://github.com/dfinity/cla/issues/424#issuecomment-1883433708)

Thank you. Can you add a file to the repo instead of calling a link for the logo?

2024-01-12 16:08 UTC, jdchibuk commented
got it - added to img/showcase/ folder - let me know if this works - appreciate the help!

2024-01-12 17:42 UTC, jennifertrin commented
> should be updated for format now
> 
> here is CLA confirmation: [dfinity/cla#424 (comment)](https://github.com/dfinity/cla/issues/424#issuecomment-1883433708)



> got it - added to img/showcase/ folder - let me know if this works - appreciate the help!

Yes, this works! Thank you!

2024-01-12 17:42 UTC, jennifertrin approved these changes

2024-01-12 17:43 UTC, merged