ICSoccerWorld Added to showcase
dfinity/portal pull request #2393
Opened 2024-01-24 23:55 UTC by ktimam

Thank you for your contribution to the IC Developer Portal.
Before submitting your Pull Request, please make sure that:

- [ ] You have updated the [`.github/CODEOWNERS`](https://github.com/dfinity/portal/blob/master/.github/CODEOWNERS) file according to your changes.
- [ ] You have registered new documents to [`/sidebars.js`](https://github.com/dfinity/portal/blob/master/sidebars.js) if any.

2024-01-24 23:56 UTC, sa-github-api commented
Dear @ktimam,

In order to potentially merge your code in this open-source repository and therefore proceed with your contribution, we need to have your approval on DFINITY's [CLA](https://github.com/dfinity/cla/blob/main/CLA.md).

If you decide to agree with it, please visit this [issue](https://github.com/dfinity/cla/issues/433) and read the instructions there. Once you have signed it, re-trigger the workflow on this PR to see if your code can be merged.

— The DFINITY Foundation

2024-01-25 06:58 UTC, letmejustputthishere requested changes

2024-01-25 06:58 UTC, letmejustputthishere commented on showcase.json
> +  "description": "Soccer simulation built for ICP using ICPP. Based on code sample from book "AI Game Programming by Example". Demo is built in C++ and uses Jolt physics Engine.",
```suggestion
  "description": "Soccer simulation built for ICP using ICPP. Based on code sample from book \"AI Game Programming by Example\". Demo is built in C++ and uses Jolt physics Engine.",
```

2024-01-25 06:59 UTC, letmejustputthishere approved these changes

2024-01-25 07:22 UTC, merged