update the docs for rearranged args
dfinity/portal pull request #372
Opened 2022-08-05 16:51 UTC by adamspofford-dfinity

dfinity/sdk#2369 moved middle-of-the-command named arguments to the end of the command. This updates the docs to reflect the new CLI interface.

2022-11-23 00:58 UTC, ericswanson-dfinity commented on docs/developer-docs/build/backend/access-control.md
> +        dfx canister call --wallet="$(dfx identity get-wallet)" access_hello assign_role '((principal "c5wa6-3irl7-tuxuo-4vtyw-xsnhw-rv2a6-vcmdz-bzkca-vejmd-327zo-wae"),opt variant{admin})'
```suggestion
        dfx canister call access_hello assign_role '((principal "c5wa6-3irl7-tuxuo-4vtyw-xsnhw-rv2a6-vcmdz-bzkca-vejmd-327zo-wae"),opt variant{admin})' --wallet="$(dfx identity get-wallet)" 
```

2022-11-23 01:01 UTC, ericswanson-dfinity commented on docs/developer-docs/build/cdks/cdk-rs-dfinity/rust-profile.md
> +    dfx canister call --identity Miles rust_profile_backend update '(record {name = "Miles"; description = "Great Dane"; keywords = vec {"Boston"; "mantle"; "three-legged"}})'
```suggestion
    dfx canister call rust_profile_backend update '(record {name = "Miles"; description = "Great Dane"; keywords = vec {"Boston"; "mantle"; "three-legged"}})' --identity Miles 
```

2022-11-23 01:01 UTC, ericswanson-dfinity commented on docs/developer-docs/build/cdks/cdk-rs-dfinity/rust-profile.md
> +    dfx canister call --identity Miles rust_profile_backend getSelf
```suggestion
    dfx canister call rust_profile_backend getSelf --identity Miles
```

2022-11-23 01:04 UTC, ericswanson-dfinity requested changes
Just a couple spots left where `--network` can go after all of the positionals

2024-03-08 22:18 UTC, jessiemongeon1 commented
This PR appears to be outdated/not needed. Closing this PR to clean up the repo. Please feel free to reopen if you think this should be revisited.

2024-03-08 22:18 UTC, closed without merging