Add Blockchain Bingo to Ecosystem Showcase
dfinity/portal pull request #3888
Opened 2024-12-14 13:28 UTC by dickhery

# 🎉 Bingo on the Internet Computer 🎉

Welcome to **Blockchain Bingo** – an exciting decentralized Bingo game built on the Internet Computer Protocol (ICP)! Dive into a fair, transparent, and engaging gaming experience where you can play against users from around the world directly on the blockchain. Whether you're aiming for a **Standard** win or going for a complete **Blackout**, our platform ensures a seamless and fun experience for all players.

## 📖 Table of Contents

- [✨ Description](#description)
  - [🎲 How It Works](#how-it-works)
- [🕹️ How to Play](#how-to-play)
- [🚀 Features](#features)
- [📊 Game Types](#game-types)
- [💡 What is ICP?](#what-is-icp)
- [🛠️ User Guides](#user-guides)
  - [🔑 Creating or Changing Your Username](#creating-or-changing-your-username)
  - [🎮 Hosting a Game](#hosting-a-game)
    - [💸 Financial Breakdown Example](#financial-breakdown-example)
  - [🔒 Creating Private Games](#creating-private-games)
- [💰 Financial Breakdown](#financial-breakdown)
- [💻 Installation](#installation)
- [🛠️ Deployment](#deployment)
  - [Deploying to the Internet Computer](#deploying-to-the-internet-computer)
- [🏃‍♂️ Running Locally](#running-locally)
- [⚙️ Frontend Environment Variables](#frontend-environment-variables)
- [📦 Dependencies](#dependencies)
  - [Backend Dependencies](#backend-dependencies)
  - [Frontend Dependencies](#frontend-dependencies)
- [🌐 Geolocation API](#geolocation-api)
- [🔄 Re-deployment Policy](#re-deployment-policy)
- [🛠️ For Developers](#for-developers)
- [📬 Contact Page](#contact-page)
- [📝 Credits](#credits)
- [📄 License](#license)

## Description

**Blockchain Bingo** is a decentralized application (dApp) that brings the classic game of Bingo to the blockchain. Leveraging the power of the Internet Computer, Bingo offers a secure and transparent platform where players can generate unique Bingo cards, participate in real-time games, and experience the thrill of winning without any centralized authority.

### 🎲 How It Works

1. **Authentication:** Players log in securely using Internet Identity.
2. **Card Generation:** Each player generates a unique 5x5 Bingo card with a free center space.
3. **Game Types:** Admins can choose between two win types:
   - **Standard:** Achieve five numbers in a row, column, or diagonal.
   - **Blackout:** Mark all numbers on your card.
4. **Gameplay:** Admins draw numbers sequentially, and all players' interfaces update in real-time.
5. **Winning:** Players can check their cards against called numbers to determine if they've won based on the selected game type.

## How to Play

1. **Login:** Use your Internet Identity to authenticate and join the game.
2. **Generate Your Card:** Click on the "View My Card" button to receive your unique Bingo card.
3. **Choose Game Type (Admin Only):** If you're the admin, select between **Standard** or **Blackout** win types before starting the game.
4. **Start the Game (Admin Only):** Begin the game, and the admin can start drawing numbers.
5. **Mark Your Numbers:** As numbers are drawn, mark them on your Bingo card.
6. **Check for Win:** Once enough numbers are drawn, use the "Check Bingo" button to see if you've won.
7. **Celebrate Victory:** If you meet the win condition, your Principal ID will be displayed as the winner, and the game will conclude.

## Features

- **Unique Bingo Cards:** Every player gets a distinct Bingo card for each game.
- **Multiple Win Types:** Choose between **Standard** and **Blackout** game modes.
- **Real-Time Updates:** Numbers drawn by the admin are instantly reflected across all players' interfaces.
- **Admin Controls:** Admins can start, reset, and control the flow of the game.
- **Secure Authentication:** Utilize Internet Identity for safe and secure user logins.
- **Transparent Gameplay:** All game actions and states are recorded on the blockchain for complete transparency.
- **Real-Time Chat Rooms:** Communicate and strategize with other players within the game's dedicated chat room.
- **ICP Balance Management:** View your ICP balance, transfer funds to other users, and manage your account seamlessly within the app.
- **Geoblocking:** Ensure compliance with regional regulations by enabling geoblocking, preventing unauthorized access to paid games.
- **Responsive Design:** Enjoy a seamless gaming experience across all devices, whether you're on a desktop, tablet, or mobile.
- **Audio Features:** Enable audio to hear numbers being called out during the game, enhancing the immersive experience.
- **Contact Page:** Reach out to the team or leave feedback through our integrated contact page.

## Game Types

**Blockchain Bingo** offers two exciting game types: **Standard** and **Blackout**. Each game type provides a unique Bingo experience tailored to different player preferences.

- **Standard Bingo:**
  - **Winning Criteria:** Achieve five numbers in a row horizontally, vertically, or diagonally.
  - **Gameplay:** Requires strategic placement and timely marking of numbers.

- **Blackout Bingo:**
  - **Winning Criteria:** Mark all squares on your Bingo card.
  - **Gameplay:** Offers a more challenging and rewarding experience for avid Bingo enthusiasts.

## What is ICP?

The **Internet Computer Protocol (ICP)** is a revolutionary blockchain technology that enables the creation of decentralized applications (dApps) with enhanced scalability, speed, and security. By leveraging ICP, **Blockchain Bingo** operates seamlessly on-chain, ensuring transparent game mechanics, secure transactions, and a trustless environment where players can enjoy Bingo without intermediaries.

## User Guides

### 🔑 Creating or Changing Your Username

Navigate to the **Chat Room** within any game and click on the **Create Username** or **Change Username** button. Follow the prompts to set or update your display name, enhancing your interaction within the community.

### 🎮 Hosting a Game

Hosting your own Bingo game is simple and rewarding. Follow these steps to set up a game that attracts players and offers enticing rewards:

1. **Choose a Game Name:** Select a unique and catchy name that reflects the theme or atmosphere of your game.
2. **Set the Entry Price:** Determine the price for each Bingo card. Remember, when you set the price in the Host Bingo screen, an additional **0.0002 ICP** is added to cover network fees required for user registration.
3. **Define the Host Percentage:** Decide on the percentage of the total pot you wish to retain as the host. This percentage is taken after a **2.5% service fee** is deducted from the total card price. For example, if you set a host percentage of **10%** on a card price of **1 ICP**, the service fee would be **0.025 ICP**, leaving **0.975 ICP**. Your host percentage would then be **0.0975 ICP**, and the remaining **0.8775 ICP** would be allocated as the prize pool for the winner.
4. **Create Private Games:** Enhance exclusivity by adding a password to your game. Players will need to enter this password before registering, ensuring only authorized participants can join.

By hosting a game, you not only create an engaging experience for players but also earn a share of the prize pool, making it a rewarding endeavor.

#### 💸 Financial Breakdown Example

- **Card Price:** 1 ICP
- **Additional ICP Fees:** 0.0002 ICP (covers two transactions at 0.0001 ICP each)
- **Service Fee (2.5%):** 0.025 ICP
- **Amount After Service Fee:** 0.975 ICP
- **Host Percentage (10%):** 0.0975 ICP
- **Prize Pool Allocation:** 0.8775 ICP

This ensures that both the host and the platform are fairly compensated while providing a substantial prize for the winner.

### 🔒 Creating Private Games

To create a private game, add a password during the game setup process in the Host Bingo screen. This password will be required for players to join the game, ensuring that only invited or authorized participants can register and play.

## Financial Breakdown

Understanding how funds are managed within **Blockchain Bingo** ensures transp [...]

2024-12-14 13:33 UTC, dickhery commented
I, dickhery, hereby agree to the DFINITY Foundation's CLA.

2025-01-07 17:39 UTC, dickhery reviewed
No idea if I'm doing this right but what's the worst thing that could happen right?

2025-01-07 18:34 UTC, jennifertrin commented on showcase.json
> +    "logo": "/static/img/showcase/blockchain-bingo_logo.png",
Can you please upload an SVG instead?

2025-01-07 18:36 UTC, jennifertrin requested changes

2025-01-07 18:36 UTC, jennifertrin commented on showcase.json
> +    "twitter": "https://x.com/richard_hery",
Can you please update the Twitter with a product Twitter? We advise using a product Twitter instead of a personal account.

2025-01-07 18:36 UTC, jennifertrin commented on showcase.json
> +    "screenshots": ["static/img/showcase/blockchain-bingo_screenshot1.jpg", "/static/img/showcase/blockchain-bingo_screenshot2.jpg"]
Can you please remove these screenshots? The screenshots don't render on the ecosystem page unless it is a featured project

2025-01-07 20:01 UTC, dickhery commented on showcase.json
> +    "logo": "/static/img/showcase/blockchain-bingo_logo.png",
I have changed the file from png to svg.

2025-01-07 20:02 UTC, dickhery commented on showcase.json
> +    "twitter": "https://x.com/richard_hery",
I just removed the Twitter line instead. I do not have a page for Blockchain Bingo yet.

2025-05-25 13:43 UTC, dickhery commented
☹️

2025-06-12 19:30 UTC, StepankaHru commented
Closing this PR, changes to the ecosystem page will be reflected later today

2025-06-12 19:30 UTC, closed without merging