Update docusaurus.config.js
dfinity/portal pull request #836
Opened 2022-11-23 04:19 UTC by dprats

Adding the support link to the top menu

right now it is buried in the footer so not many people see it.

2022-11-23 13:20 UTC, harpa12 requested changes
Placement is fine but please rename to ICP Support Resources

2022-11-24 07:05 UTC, sesi200 approved these changes

2022-11-24 12:50 UTC, harpa12 approved these changes

2022-11-24 12:50 UTC, merged

2022-11-24 12:50 UTC, csepreghy approved these changes